import { imageIcon } from "../assets/ImageExport";

export const menuIconName = [
    { slno: 1, route: "/Menu/Admin", iconName: imageIcon.icon49, name: 'Admin' },
    { slno: 2, route: "/Menu/Outpatient", iconName: imageIcon.icon16, name: 'Out Patient' },
    { slno: 3, route: "/Menu/Test", iconName: imageIcon.icon30, name: 'Care Desk' },
    { slno: 4, route: "/Menu/Inpatient", iconName: imageIcon.icon21, name: 'In Patient' },
    { slno: 5, route: "/Menu/LabGeneralBill", iconName: imageIcon.icon17, name: 'Lab - General Billing' },
    { slno: 6, route: "/Menu/PharmacyBilling", iconName: imageIcon.icon20, name: 'Pharmacy Billing' },
    { slno: 7, route: "/Menu/Test", iconName: imageIcon.icon1, name: 'Web EMR' },
    { slno: 8, route: "/Menu/Test", iconName: imageIcon.icon19, name: 'General Store' },
    { slno: 9, route: "/Menu/Test", iconName: imageIcon.icon14, name: 'Patient Feedback' },
    { slno: 10, route: "/Menu/Test", iconName: imageIcon.icon19, name: 'Pharmacy Store' },
    { slno: 11, route: "/Menu/Test", iconName: imageIcon.icon18, name: 'Lab Result' },
    { slno: 12, route: "/Menu/Test", iconName: imageIcon.icon2, name: 'Nursing Station' },
    { slno: 13, route: "/Menu/Test", iconName: imageIcon.icon34, name: 'Medical records' },
    { slno: 14, route: "/Menu/Test", iconName: imageIcon.icon15, name: 'Insurance' },
    { slno: 15, route: "/Menu/Mis", iconName: imageIcon.icon50, name: 'MIS' },
    { slno: 16, route: "/Menu/Test", iconName: imageIcon.icon7, name: 'Blood Bank' },
    { slno: 17, route: "/Menu/Test", iconName: imageIcon.icon5, name: 'House Keeping' },
    { slno: 18, route: "/Menu/Test", iconName: imageIcon.icon9, name: 'Casualty' },
    { slno: 19, route: "/Menu/Test", iconName: imageIcon.icon29, name: 'Theatre' },
    { slno: 20, route: "/Menu/Test", iconName: imageIcon.icon49, name: 'General Master' },
    { slno: 21, route: "/Menu/DashBoard", iconName: imageIcon.icon49, name: 'DashBoard' },
]
